#test CI CD ok
image: node:16.x

stages:
  - test
  - gusti

test:
  stage: test
  script:
    - npm install
    - "NODE_ENV=development npx sequelize db:create"
    - "NODE_ENV=development npx sequelize db:migrate"
    - "NODE_ENV=development npx sequelize db:seed:all"
    - "NODE_ENV=development npm test"
    only:
    - test


gusti:
  type: deploy
  stage: gusti
  image: ruby:3
  script:
    - brew install brew-gem
    - brew gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_GUSTI --api-key=$HEROKU_API_KEY_GUSTI
  only:
    - gusti
