# We will try to use machine (Linux) that includes node.js (temporary)
image: node:latest

stages:
  - test
  - staging

test:
  type: test
  stage: test
  services:
    - mysql:latest # Add postgres service in Gitlab to test the code
  script:
    - npm i
    # - npx sequelize db:create
    # - npx sequelize db:migrate
    # - npx sequelize db:seed:all
    - npm run test # It will run test in Gitlab before it upload to heroku
  only:
    - sagipul-tugas

staging:
  type: deploy
  stage: staging
  image: ruby:3
  script:
    # dpl is package to deploy to heroku
    - apt-get update
    - apt-get install ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
  only:
    - sagipul-tugas
