#test CI CD ok
image: node:16.x

stages:
  - test
  - gusti

test:
  type: test
  stage: test
  services:
    - postgres:14-alpine
  script:
    - npm install
    - "NODE_ENV=development npm test"
  only:
    - test

gusti:
  type: deploy
  stage: gusti
  image: ruby:3
  script:
    - brew install brew-gem
    - brew gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_GUSTI --api-key=$HEROKU_API_KEY_GUSTI
  only:
    - gusti
