#test CI CD tes
image: node:16.x

stages:
  - test
  - gusti

test:
  stage: test
  script:
    - npm install
    - "npm test"

gusti:
  type: deploy
  stage: gusti
  image: ruby:3
  script:
    - apt-get update -yq
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_GUSTI --api-key=$HEROKU_API_KEY_GUSTI
  only:
    - gusti
