#test CI CD ok
image: node:16.x

stages:
  - test
  - gusti

test:
  type: test
  stage: test
  services:
    - postgres:latest

variables:
    RAILS_ENV: test
    POSTGRES_DB: sekwfwwf
    POSTGRES_USER: sekwfwwf
    POSTGRES_PASSWORD: 3ega02l1jwS68gkobERhQmgvwvU2RLCC
    POSTGRES_HOST_AUTH_METHOD: trust
    DATABASE_URL: "postgres://sekwfwwf:3ega02l1jwS68gkobERhQmgvwvU2RLCC@john.db.elephantsql.com/sekwfwwf"
script:
    - npm install
    - npm run test
  only:
    - test

gusti:
  type: deploy
  stage: gusti
  image: ruby:3
  script:
    - brew install brew-gem
    - brew gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_GUSTI --api-key=$HEROKU_API_KEY_GUSTI
  only:
    - gusti
