# We will try to use machine (Linux) that includes node.js (temporary)
image: node:16-alpine

cache:
  paths:
    - node_modules/

stages:
  - test
  - staging

test:
  stage: test
  script:
    - npm install
    - "npm test"

staging:
  type: deploy
  stage: staging
  image: ruby:3 # Using ruby image to deploy to heroku 
  script:
    # dpl is package to deploy to heroku
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_API_KEY
  only:
    - staging
