#test CI CD tes oke
image: node:16.x

stages:
  - test
  - gusti_arsyad

test:
  stage: test
  script:
    - npm install
    - "npm test"

gusti_arsyad:
  type: deploy
  stage: gusti_arsyad
  image: ruby:3
  script:
    - apt-get update -yq
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_GUSTI --api-key=$HEROKU_API_KEY_GUSTI
  only:
    - gusti_arsyad
