image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - test
  - init
  - staging

test:
  stage: test
  script:
    - npm install
    - "npm test"

init:
  stage: init
  image: node:14.18.0
  script:
    - npm install

staging:
  type: deploy
  stage: staging
  image: node:14.18.0
  script:
    - git push https://$HEROKU_USER:$HEROKU_API_KEY@https://git.heroku.com/timdevent.git HEAD:master
  only:
    - master
