image: node:latest

stages:
  - test
  - production

test:
  stage: test
  # services:
  #   - postgres:12.2-alpine

  # variables:
  #   POSTGRES_DB: $gerrympa_test
  #   POSTGRES_USER: $postgres
  #   POSTGRES_PASSWORD: $Bantenku1
  #   POSTGRES_HOST_AUTH_METHOD: trust

  script:
    - npm install
    # - npx sequelize-cli db:create
    # - npx sequelize-cli db:migrate
    - "npm test"
production:
  type: deploy
  stage: production
  image: ruby:3 # Using ruby image to deploy to heroku
  script:
    # dpl is package to deploy to heroku
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_API_KEY
  only:
    - production
# vv