image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - test
  - init
  - staging

test:
  stage: test
  script:
    - npm install
    - "npm test"

init:
  stage: init
  image: node:14.18.0
  script:
    - npm install

staging:
  type: deploy
  stage: staging
  image: node:14.18.0
  script:
    - --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
  only:
    - master
